### ISSUE TITLE
Store reliability using either Politifact or Media Bias Fact Check

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_backend#29]
Ideally, we'd use politifact (http://static.politifact.com/api/v2apidoc.html) to analyze reliability on a per article basis

As a temporary solution, we could also use Media Bia Factcheck to indicate reliability on a per-publication measure:
- e.g.: https://mediabiasfactcheck.com/breitbart/ does have a section that notes "factual reporting"

Visual-wise, we could have a note or a hoverable exclamation mark that will show that information upon hover over

**Comment by cssherry** [comment]
After this issue is resolved, can then implement https://github.com/spectrum-app/spectrum_chrome_app/issues/32

**Comment by geraldgordinier** [comment]
I will get you some visual for this.

**Comment by geraldgordinier** [comment]
I also realize I provided the feedback designs for the "Future" of the news article, so gonna redo that slightly

**Comment by jgerminario** [comment]
This is on the roadmap, added to the wiki here: https://spectrumapp.atlassian.net/wiki/display/PROD/Spectrum+Roadmap, going to close this ticket for now since requirements haven't been speced out, which we will do on the wiki or Trello (I'm trying to move us away from using GitHub for non-specific tasks).
